# Generated by Django 4.2.19 on 2026-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_supportmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Filial nomi')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat/Shahar')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('director_name', models.CharField(blank=True, max_length=200, verbose_name='Direktori ismi')),
                ('director_image', models.ImageField(blank=True, null=True, upload_to='directors/', verbose_name='Direktori rasmi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('is_main', models.BooleanField(default=False, verbose_name='Bosh filial')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='103', max_length=20, verbose_name='Emergency telefon')),
                ('phone_office', models.CharField(blank=True, max_length=20, verbose_name='Qabulxona telefoni')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('working_hours', models.CharField(default='24/7', max_length=100, verbose_name='Ish vaqti')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': "Aloqa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('media_type', models.CharField(choices=[('photo', 'Rasm'), ('video', 'Video')], max_length=10, verbose_name='Turi')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Rasm')),
                ('video_url', models.URLField(blank=True, help_text='YouTube yoki boshqa video linki', null=True, verbose_name='Video URL')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereya',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Qisqa tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Xizmati nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('icon', models.CharField(default='icon', help_text='Font Awesome class nomi', max_length=50, verbose_name='Icon')),
                ('order', models.IntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order'],
            },
        ),
    ]
