# Generated by Django 4.2.30 on 2026-09-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_errorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram havolasi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Faqat interaktiv xarita uchun kerak. Masalan: qarshi-shahar, koson, kitob...', max_length=60, verbose_name="Xarita ID (SVG ID bilan bir xil bo'lishi kerak)"),
        ),
        migrations.AddField(
            model_name='branch',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram havolasi'),
        ),
    ]
