# Generated by Django 4.2.30 on 2026-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_branch_instagram_branch_slug_branch_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkoActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Qisqa tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ekofaol/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
            ],
            options={
                'verbose_name': 'Ekofaol post',
                'verbose_name_plural': 'Ekofaol xodim',
                'ordering': ['-created_at'],
            },
        ),
    ]
