# Generated by Django 4.2.30 on 2026-09-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.Sh.')),
                ('position', models.CharField(max_length=300, verbose_name='Lavozimi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('reception_day', models.CharField(blank=True, help_text='Masalan: Chorshanba 14:00-16:00', max_length=100, verbose_name='Qabul kuni/vaqti')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Markaziy apparat',
                'ordering': ['order', 'id'],
            },
        ),
    ]
