# Generated by Django 4.2.30 on 2026-09-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCorruptionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('body', models.TextField(verbose_name='Matn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Korrupsiyaga qarshi kurashish mavzusi',
                'verbose_name_plural': 'Korrupsiyaga qarshi kurashish',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
