# Generated by Django 4.2.30 on 2026-09-08 12:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_anticorruptionpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticorruptionpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default', verbose_name='Matn'),
        ),
    ]