# Generated by Django 4.2.30 on 2026-09-08 15:32

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_anticorruptionpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticorruptionpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Matn'),
        ),
    ]
