# Generated by Django 4.2.30 on 2026-09-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_anticorruptionpost_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Qisqa tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='laws/', verbose_name='Rasm')),
                ('url', models.URLField(verbose_name='Havola (qonun matni joylashgan sahifa)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Qonun',
                'verbose_name_plural': 'Qonunlar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
