# Generated by Django 4.2.30 on 2026-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_governmentdecree'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Qisqa tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='normative/', verbose_name='Rasm (karta uchun)')),
                ('url', models.URLField(blank=True, help_text="Agar hujjat boshqa saytda joylashgan bo'lsa, shu yerga havolani kiriting.", verbose_name='Tashqi havola')),
                ('file', models.FileField(blank=True, help_text="Agar hujjat faylini saytga yuklamoqchi bo'lsangiz, shu yerdan tanlang.", null=True, upload_to='normative_files/', verbose_name='Fayl (PDF, Word, Excel, TXT, rasm)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Normativ hujjat',
                'verbose_name_plural': 'Markaz normativ hujjatlari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
