# Generated by Django 4.2.30 on 2026-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_financialtransparencydocument_hrpolicydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityResultsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Qisqa tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_results/', verbose_name='Rasm (karta uchun)')),
                ('url', models.URLField(blank=True, help_text="Agar hujjat boshqa saytda joylashgan bo'lsa, shu yerga havolani kiriting.", verbose_name='Tashqi havola')),
                ('file', models.FileField(blank=True, help_text="Agar hujjat faylini saytga yuklamoqchi bo'lsangiz, shu yerdan tanlang.", null=True, upload_to='activity_results_files/', verbose_name='Fayl (PDF, Word, Excel, TXT, rasm)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Faoliyat va natijalar axboroti',
                'verbose_name_plural': "Faoliyat va natijalar to'g'risidagi axborot",
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalLegalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Qisqa tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='org_legal/', verbose_name='Rasm (karta uchun)')),
                ('url', models.URLField(blank=True, help_text="Agar hujjat boshqa saytda joylashgan bo'lsa, shu yerga havolani kiriting.", verbose_name='Tashqi havola')),
                ('file', models.FileField(blank=True, help_text="Agar hujjat faylini saytga yuklamoqchi bo'lsangiz, shu yerdan tanlang.", null=True, upload_to='org_legal_files/', verbose_name='Fayl (PDF, Word, Excel, TXT, rasm)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Tashkiliy-huquqiy ma'lumot",
                'verbose_name_plural': "Tashkiliy-huquqiy ma'lumotlar",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
