# Generated by Django 4.2.30 on 2026-09-12 18:01

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_activityresultsinfo_organizationallegalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text="Maqolalar ro'yxatida va sahifa boshida ko'rsatiladigan sarlavha rasmi.", null=True, upload_to='posts/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Matn'),
        ),
    ]
