# Generated by Django 4.2.30 on 2026-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_image_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AloqaMalumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qabulxona_telefon', models.CharField(max_length=30, verbose_name='Qabulxona telefoni')),
                ('shoshilinch_telefon', models.CharField(max_length=30, verbose_name='Shoshilinch telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ish_vaqti', models.CharField(max_length=200, verbose_name='Ish vaqti')),
                ('tavsif', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
            ],
            options={
                'verbose_name': "Aloqa ma'lumoti",
                'verbose_name_plural': "Call-markaz ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Fikr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('shahar', models.CharField(max_length=100, verbose_name='Shahar/Tuman')),
                ('matn', models.TextField(verbose_name='Fikr matni')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Fikr',
                'verbose_name_plural': 'Bemorlar fikrlari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Galereya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='galereya/', verbose_name='Rasm')),
                ('nomi', models.CharField(max_length=100, verbose_name='Rasm nomi')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Markazimizdan lavhalar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Maqsad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Emoji')),
                ('sarlavha', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('matn', models.TextField(verbose_name='Tavsif')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Maqsad',
                'verbose_name_plural': 'Maqsad va vazifalar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Emoji')),
                ('son', models.CharField(max_length=20, verbose_name='Son (masalan: 60-100, 24/7, 13, 100%)')),
                ('matn', models.CharField(max_length=200, verbose_name='Tavsif matni')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Bizning jamoamiz (Statistika)',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='TarixEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.CharField(max_length=20, verbose_name='Yil (masalan: 2025 yoki 2025-2026)')),
                ('sarlavha', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('matn', models.TextField(verbose_name='Tavsif')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Tarix voqeasi',
                'verbose_name_plural': 'Markaz tarixi',
                'ordering': ['tartib'],
            },
        ),
    ]
