# Generated by Django 4.2.30 on 2026-09-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_aloqamalumot_fikr_galereya_maqsad_statistika_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AloqaMalumot',
        ),
        migrations.DeleteModel(
            name='Fikr',
        ),
        migrations.DeleteModel(
            name='Galereya',
        ),
        migrations.DeleteModel(
            name='Maqsad',
        ),
        migrations.DeleteModel(
            name='Statistika',
        ),
        migrations.DeleteModel(
            name='TarixEvent',
        ),
    ]
