# Generated by Django 4.2.30 on 2026-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_delete_aloqamalumot_delete_fikr_delete_galereya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Yil (masalan: 2025 yoki 2025–2026)')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Matn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Timeline hodisasi',
                'verbose_name_plural': 'Markaz tarixi (Timeline)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
