# Generated by Django 4.2.30 on 2026-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_timelineevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Tarix voqeasi', 'verbose_name_plural': 'Markaz tarixi (Timeline)'},
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Kichik raqam yuqorida chiqadi', verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='year',
            field=models.CharField(help_text='Masalan: 2025 yoki 2025 – 2026 yoki Bugungi kun', max_length=20, verbose_name='Yil'),
        ),
    ]
