# Generated by Django 4.2.30 on 2026-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Masalan: 👨\u200d⚕️ yoki 🚑 (emoji klaviaturadan tanlang)', max_length=10, verbose_name='Icon (emoji)')),
                ('number', models.CharField(help_text='Masalan: 60–100 yoki 24/7 yoki 100%', max_length=20, verbose_name='Raqam/qiymat')),
                ('label', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Jamoa statistikasi',
                'verbose_name_plural': 'Bizning jamoamiz (statistika)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
