# Generated by Django 4.2.30 on 2026-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_teamstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Rasm'), ('video', 'Video')], default='photo', max_length=10, verbose_name='Turi')),
                ('image', models.ImageField(blank=True, help_text="Faqat 'Rasm' turi tanlansa yuklang", null=True, upload_to='about_media/photos/', verbose_name='Rasm')),
                ('video', models.FileField(blank=True, help_text="Faqat 'Video' turi tanlansa yuklang", null=True, upload_to='about_media/videos/', verbose_name='Video fayl')),
                ('caption', models.CharField(help_text='Rasm/video tagida chiqadigan matn', max_length=255, verbose_name='Qisqacha tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Markaz fotolavhasi',
                'verbose_name_plural': 'Markazimizdan lavhalar (Rasm/Video)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
