# Generated by Django 4.2.30 on 2026-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_aboutmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmedia',
            name='video',
        ),
        migrations.AddField(
            model_name='aboutmedia',
            name='video_url',
            field=models.URLField(blank=True, help_text="Faqat 'Video' turi tanlansa YouTube havolasini kiriting (masalan: https://www.youtube.com/watch?v=XXXXXXXXXXX)", null=True, verbose_name='Video havolasi'),
        ),
    ]
