# Generated by Django 4.2.30 on 2026-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_aboutmedia_video_aboutmedia_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('location', models.CharField(blank=True, help_text='Masalan: Qarshi shahri', max_length=100, verbose_name='Shahar/tuman')),
                ('text', models.TextField(verbose_name='Fikr matni')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan (saytda chiqadi)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
            ],
            options={
                'verbose_name': 'Bemor fikri',
                'verbose_name_plural': 'Bemorlar fikrlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
