# Generated by Django 4.2.30 on 2026-09-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Masalan: 🎯 👥 ⚕️ 🔬 — emoji klaviaturadan yoki emojipedia.org dan nusxa oling', max_length=10, verbose_name='Ikonka (emoji)')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Maqsad va vazifa',
                'verbose_name_plural': 'Bizning maqsad va vazifalarimiz',
                'ordering': ['order', 'id'],
            },
        ),
    ]
