# Generated by Django 4.2.30 on 2026-09-23 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_missiongoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name="Ko'rib chiqildi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yangi foydalanuvchi bildirishnomasi',
                'verbose_name_plural': "Yangi ro'yxatdan o'tgan foydalanuvchilar",
                'ordering': ['-created_at'],
            },
        ),
    ]
