# Generated by Django 4.2.30 on 2026-09-23 13:27

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_newusernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmedia',
            name='caption_en',
            field=models.CharField(help_text='Rasm/video tagida chiqadigan matn', max_length=255, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutmedia',
            name='caption_ru',
            field=models.CharField(help_text='Rasm/video tagida chiqadigan matn', max_length=255, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutmedia',
            name='caption_uz',
            field=models.CharField(help_text='Rasm/video tagida chiqadigan matn', max_length=255, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutmedia',
            name='caption_uz_cyrl',
            field=models.CharField(help_text='Rasm/video tagida chiqadigan matn', max_length=255, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='activityresultsinfo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='activityresultsinfo',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='activityresultsinfo',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='activityresultsinfo',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='activityresultsinfo',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='activityresultsinfo',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='activityresultsinfo',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='activityresultsinfo',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='anticorruptionpost',
            name='body_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='anticorruptionpost',
            name='body_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='anticorruptionpost',
            name='body_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='anticorruptionpost',
            name='body_uz_cyrl',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='anticorruptionpost',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='anticorruptionpost',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='anticorruptionpost',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='anticorruptionpost',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='branch',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Filial nomi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Filial nomi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Filial nomi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Filial nomi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Viloyat/Shahar'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Viloyat/Shahar'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Viloyat/Shahar'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region_uz_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Viloyat/Shahar'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours_en',
            field=models.CharField(default='24/7', max_length=100, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours_ru',
            field=models.CharField(default='24/7', max_length=100, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours_uz',
            field=models.CharField(default='24/7', max_length=100, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours_uz_cyrl',
            field=models.CharField(default='24/7', max_length=100, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='ekoactivity',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='ekoactivity',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='ekoactivity',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='ekoactivity',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='ekoactivity',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ekoactivity',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ekoactivity',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ekoactivity',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='financialtransparencydocument',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='financialtransparencydocument',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='financialtransparencydocument',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='financialtransparencydocument',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='financialtransparencydocument',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='financialtransparencydocument',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='financialtransparencydocument',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='financialtransparencydocument',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_uz_cyrl',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='governmentdecree',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='governmentdecree',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='governmentdecree',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='governmentdecree',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='governmentdecree',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='governmentdecree',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='governmentdecree',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='governmentdecree',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='hrpolicydocument',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='hrpolicydocument',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='hrpolicydocument',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='hrpolicydocument',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='hrpolicydocument',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='hrpolicydocument',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='hrpolicydocument',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='hrpolicydocument',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='law',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='law',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='law',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='law',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='law',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='law',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='law',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='law',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='missiongoal',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='missiongoal',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='missiongoal',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='missiongoal',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='missiongoal',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='missiongoal',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='missiongoal',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='missiongoal',
            name='title_uz_cyrl',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='organizationallegalinfo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='organizationallegalinfo',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='organizationallegalinfo',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='organizationallegalinfo',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='organizationallegalinfo',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='organizationallegalinfo',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='organizationallegalinfo',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='organizationallegalinfo',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_uz_cyrl',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz_cyrl',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='presidentialdecree',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='presidentialdecree',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='presidentialdecree',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='presidentialdecree',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AddField(
            model_name='presidentialdecree',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='presidentialdecree',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='presidentialdecree',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='presidentialdecree',
            name='title_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position_uz_cyrl',
            field=models.CharField(max_length=300, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='label_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='label_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='label_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='label_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
