# Generated by Django 4.2.30 on 2026-09-26 06:53

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_aboutmedia_caption_en_aboutmedia_caption_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Qisqa tavsifi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Qisqa tavsifi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uz_cyrl',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Qisqa tavsifi'),
        ),
    ]
