# Generated by Django 4.2.30 on 2026-09-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0033_alter_news_description_alter_news_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Obyekt ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('icon', models.CharField(default='🔔', max_length=10, verbose_name='Ikonka')),
                ('manual_url', models.CharField(blank=True, max_length=500, verbose_name="Havola (qo'lda kiritilsa, avtomatikdan ustun turadi)")),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol (saytda ko'rinsin)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model turi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
