# Generated by Django 4.2.30 on 2026-09-30 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin bildirishnoma', 'verbose_name_plural': 'Admin bildirishnomalar'},
        ),
        migrations.AlterModelOptions(
            name='broadcast',
            options={'verbose_name': 'Ommaviy xabar', 'verbose_name_plural': 'Ommaviy xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Murojaat', 'verbose_name_plural': 'Murojaatlar'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram foydalanuvchi', 'verbose_name_plural': 'Telegram foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Xato'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Yuborilgan'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='sent_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Yetkazildi'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=models.TextField(help_text='Barcha foydalanuvchilarga yuboriladigan xabar', verbose_name='Xabar matni'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Javob vaqti'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='tg_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram', to=settings.AUTH_USER_MODEL, verbose_name='Sayt foydalanuvchisi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Username'),
        ),
    ]
